name: Generate Datas

on:
  schedule: # execute every Monday
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: FabioDevCode
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
